"use strict";

/**
 * Solinteg MHT-25~50K-100 Modbus TCP register map.
 *
 * Source: Solinteg Modbus TCP protocol register addresses, cross-checked against
 * wills106/homeassistant-solax-modbus (custom_components/solax_modbus/plugin_solinteg.py),
 * which documents the identical INTEG-M register family (also used by Wattsonic and
 * M-TEC Energy Butler rebrands). Register addresses are NOT independently verified
 * against real hardware yet - see README "Known limitations" before relying on this
 * in production, especially for u32/s32 word order and the EMS control registers
 * (50xxx/52xxx block).
 *
 * Each entry:
 *   id       dot-path under the adapter's object tree (without adapter/instance prefix)
 *   name     human-readable name (English)
 *   address  Modbus register address, as used directly in a readHoldingRegisters() call
 *   type     "u16" | "s16" | "u32" | "s32" | "str" | "map" | "bool"
 *   length   register word count (auto-derived for u16/s16=1, u32/s32=2 unless set)
 *   scale    multiplier applied after decoding a numeric register (default 1)
 *   unit     ioBroker common.unit (optional)
 *   role     ioBroker common.role
 *   group    "fast" (5s poll, power/flow values) | "slow" (30s poll, energy counters/diagnostics)
 *   write    true if this register may be written (EMS control), default false
 *   min/max  native value range for writable numeric registers
 *   map      { rawValue: "label" } for type "map" (select-style registers)
 */

const PV_STRINGS = 4;

const pvRegisters = [];
for (let i = 1; i <= PV_STRINGS; i++) {
    const voltageAddr = 11036 + 2 * i; // 11038, 11040, 11042, 11044
    const currentAddr = voltageAddr + 1; // 11039, 11041, 11043, 11045
    const powerAddr = 11060 + 2 * i; // 11062, 11064, 11066, 11068
    pvRegisters.push(
        {
            id: `pv.string${i}.voltage`,
            name: `PV${i} Voltage`,
            address: voltageAddr,
            type: "u16",
            scale: 0.1,
            unit: "V",
            role: "value.voltage",
            group: "fast",
        },
        {
            id: `pv.string${i}.current`,
            name: `PV${i} Current`,
            address: currentAddr,
            type: "u16",
            scale: 0.1,
            unit: "A",
            role: "value.current",
            group: "fast",
        },
        {
            id: `pv.string${i}.power`,
            name: `PV${i} Power`,
            address: powerAddr,
            type: "u32",
            scale: 1,
            unit: "W",
            role: "value.power",
            group: "fast",
        },
    );
}

const registers = [
    // ---- Device info / diagnostics (slow) ----
    {
        id: "info.serialNumber",
        name: "Inverter serial number",
        address: 10000,
        type: "str",
        length: 8,
        role: "info.serial",
        group: "slow",
    },
    {
        id: "info.firmwareVersion",
        name: "Firmware version",
        address: 10011,
        type: "fw",
        length: 4,
        role: "info.firmware",
        group: "slow",
    },
    {
        id: "diag.inverterStatus",
        name: "Inverter status code",
        address: 10105,
        type: "u16",
        role: "value",
        group: "slow",
    },
    {
        id: "diag.faultFlags1",
        name: "Fault flags 1 (bitmask)",
        address: 10112,
        type: "u32",
        role: "value",
        group: "slow",
    },
    {
        id: "diag.faultFlags2",
        name: "Fault flags 2 (bitmask)",
        address: 10114,
        type: "u32",
        role: "value",
        group: "slow",
    },
    {
        id: "diag.faultFlags3",
        name: "Fault flags 3 (bitmask)",
        address: 10120,
        type: "u32",
        role: "value",
        group: "slow",
    },
    {
        id: "diag.radiatorTemperature",
        name: "Radiator temperature",
        address: 11035,
        type: "s16",
        scale: 0.1,
        unit: "°C",
        role: "value.temperature",
        group: "slow",
    },

    // ---- PV strings 1-4 (fast) ----
    ...pvRegisters,
    {
        id: "pv.totalPower",
        name: "PV total power",
        address: 11028,
        type: "u32",
        unit: "W",
        role: "value.power",
        group: "fast",
    },

    // ---- AC / Grid (fast/medium, all bucketed "fast" here) ----
    {
        id: "grid.acPower",
        name: "AC power (inverter output)",
        address: 11016,
        type: "s32",
        unit: "W",
        role: "value.power",
        group: "fast",
    },
    {
        id: "grid.frequency",
        name: "Grid frequency",
        address: 11015,
        type: "u16",
        scale: 0.01,
        unit: "Hz",
        role: "value.frequency",
        group: "fast",
    },
    {
        id: "grid.voltageL1",
        name: "Grid voltage L1",
        address: 11009,
        type: "u16",
        scale: 0.1,
        unit: "V",
        role: "value.voltage",
        group: "fast",
    },
    {
        id: "grid.voltageL2",
        name: "Grid voltage L2",
        address: 11011,
        type: "u16",
        scale: 0.1,
        unit: "V",
        role: "value.voltage",
        group: "fast",
    },
    {
        id: "grid.voltageL3",
        name: "Grid voltage L3",
        address: 11013,
        type: "u16",
        scale: 0.1,
        unit: "V",
        role: "value.voltage",
        group: "fast",
    },
    {
        id: "grid.currentL1",
        name: "Grid current L1",
        address: 11010,
        type: "u16",
        scale: 0.1,
        unit: "A",
        role: "value.current",
        group: "fast",
    },
    {
        id: "grid.currentL2",
        name: "Grid current L2",
        address: 11012,
        type: "u16",
        scale: 0.1,
        unit: "A",
        role: "value.current",
        group: "fast",
    },
    {
        id: "grid.currentL3",
        name: "Grid current L3",
        address: 11014,
        type: "u16",
        scale: 0.1,
        unit: "A",
        role: "value.current",
        group: "fast",
    },

    // ---- Meter (grid connection point) ----
    {
        id: "meter.power",
        name: "Meter power (grid connection point, +import/-export)",
        address: 11000,
        type: "s32",
        unit: "W",
        role: "value.power",
        group: "fast",
    },
    {
        id: "meter.powerL1",
        name: "Meter power L1",
        address: 10994,
        type: "s32",
        unit: "W",
        role: "value.power",
        group: "fast",
    },
    {
        id: "meter.powerL2",
        name: "Meter power L2",
        address: 10996,
        type: "s32",
        unit: "W",
        role: "value.power",
        group: "fast",
    },
    {
        id: "meter.powerL3",
        name: "Meter power L3",
        address: 10998,
        type: "s32",
        unit: "W",
        role: "value.power",
        group: "fast",
    },
    {
        id: "meter.gridImportTotal",
        name: "Grid import, total",
        address: 11004,
        type: "u32",
        scale: 0.01,
        unit: "kWh",
        role: "value.energy",
        group: "slow",
    },
    {
        id: "meter.gridExportTotal",
        name: "Grid export, total",
        address: 11002,
        type: "u32",
        scale: 0.01,
        unit: "kWh",
        role: "value.energy",
        group: "slow",
    },

    // ---- Battery ----
    {
        id: "battery.voltage",
        name: "Battery voltage",
        address: 30254,
        type: "u16",
        scale: 0.1,
        unit: "V",
        role: "value.voltage",
        group: "fast",
    },
    {
        id: "battery.current",
        name: "Battery current",
        address: 30255,
        type: "s16",
        scale: 0.1,
        unit: "A",
        role: "value.current",
        group: "fast",
    },
    {
        id: "battery.power",
        name: "Battery power (+charge/-discharge)",
        address: 30258,
        type: "s32",
        unit: "W",
        role: "value.power",
        group: "fast",
    },
    {
        id: "battery.soc",
        name: "Battery state of charge",
        address: 33000,
        type: "u16",
        scale: 0.01,
        unit: "%",
        role: "value.battery",
        group: "fast",
    },
    {
        id: "battery.soh",
        name: "Battery state of health",
        address: 33001,
        type: "u16",
        scale: 0.01,
        unit: "%",
        role: "value",
        group: "slow",
    },
    {
        id: "battery.temperature",
        name: "Battery temperature",
        address: 33003,
        type: "s16",
        scale: 0.1,
        unit: "°C",
        role: "value.temperature",
        group: "slow",
    },
    {
        id: "battery.minCellVoltage",
        name: "Minimum cell voltage",
        address: 33015,
        type: "u16",
        scale: 0.001,
        unit: "V",
        role: "value.voltage",
        group: "slow",
    },
    {
        id: "battery.minCellVoltageId",
        name: "ID of cell with minimum voltage",
        address: 33014,
        type: "u16",
        role: "value",
        group: "slow",
    },
    {
        id: "battery.maxCellVoltage",
        name: "Maximum cell voltage",
        address: 33013,
        type: "u16",
        scale: 0.001,
        unit: "V",
        role: "value.voltage",
        group: "slow",
    },
    {
        id: "battery.maxCellVoltageId",
        name: "ID of cell with maximum voltage",
        address: 33012,
        type: "u16",
        role: "value",
        group: "slow",
    },
    {
        id: "battery.chargeLimit",
        name: "Battery charge current limit (reported)",
        address: 33021,
        type: "u16",
        scale: 0.1,
        unit: "A",
        role: "value.current",
        group: "slow",
    },
    {
        id: "battery.dischargeLimit",
        name: "Battery discharge current limit (reported)",
        address: 33023,
        type: "u16",
        scale: 0.1,
        unit: "A",
        role: "value.current",
        group: "slow",
    },
    {
        id: "battery.chargeToday",
        name: "Battery charge, today",
        address: 31003,
        type: "u16",
        scale: 0.1,
        unit: "kWh",
        role: "value.energy",
        group: "slow",
    },
    {
        id: "battery.chargeTotal",
        name: "Battery charge, total",
        address: 31108,
        type: "u32",
        scale: 0.1,
        unit: "kWh",
        role: "value.energy",
        group: "slow",
    },
    {
        id: "battery.dischargeToday",
        name: "Battery discharge, today",
        address: 31004,
        type: "u16",
        scale: 0.1,
        unit: "kWh",
        role: "value.energy",
        group: "slow",
    },
    {
        id: "battery.dischargeTotal",
        name: "Battery discharge, total",
        address: 31110,
        type: "u32",
        scale: 0.1,
        unit: "kWh",
        role: "value.energy",
        group: "slow",
    },
    {
        id: "battery.manufacturer",
        name: "Battery manufacturer (BMS string)",
        address: 32020,
        type: "str",
        length: 8,
        role: "info.name",
        group: "slow",
    },
    {
        id: "battery.ratedCapacity",
        name: "Battery rated capacity",
        address: 32007,
        type: "u32",
        unit: "Wh",
        role: "value",
        group: "slow",
    },

    // ---- Energy totals ----
    {
        id: "energy.pvGenerationToday",
        name: "PV generation, today",
        address: 31005,
        type: "u16",
        scale: 0.1,
        unit: "kWh",
        role: "value.energy",
        group: "slow",
    },
    {
        id: "energy.pvGenerationTotal",
        name: "PV generation, total",
        address: 31112,
        type: "u32",
        scale: 0.1,
        unit: "kWh",
        role: "value.energy",
        group: "slow",
    },
    {
        id: "energy.houseConsumptionToday",
        name: "House consumption, today",
        address: 31006,
        type: "u16",
        scale: 0.1,
        unit: "kWh",
        role: "value.energy",
        group: "slow",
    },
    {
        id: "energy.houseConsumptionTotal",
        name: "House consumption, total",
        address: 31114,
        type: "u32",
        scale: 0.1,
        unit: "kWh",
        role: "value.energy",
        group: "slow",
    },

    // ---- EMS control registers (write, gated by native.enableEmsControl) ----
    {
        id: "ems.workingMode",
        name: "Working mode",
        address: 50000,
        type: "map",
        // role "value" is read-only per the ioBroker state-roles spec; this register is
        // writable, so it must use a "level" role instead (common.write=true).
        role: "level",
        group: "slow",
        write: true,
        map: {
            0x101: "General",
            0x102: "Economic",
            0x103: "UPS",
            0x104: "PeakShift",
            0x105: "Feed-In",
            0x200: "Off-Grid",
            0x301: "EMS ACCtrl",
            0x302: "EMS General",
            0x303: "EMS BattCtrl",
            0x304: "EMS Off-Grid",
            0x400: "ToU",
        },
    },
    {
        id: "ems.acCtrlMode",
        name: "EMS ACCtrl AC power scheduling mode",
        address: 50202,
        type: "map",
        role: "level",
        group: "slow",
        write: true,
        map: {
            0: "Off",
            1: "Total power setting",
            2: "Power setting per phase",
        },
    },
    {
        id: "ems.acCtrlTotalPower",
        name: "EMS ACCtrl total AC power setpoint",
        address: 50203,
        type: "s16",
        scale: 0.01,
        unit: "kW",
        // no "level.power" role exists in the official state-roles list (unlike
        // level.voltage/level.current/level.frequency) - "level" is the correct generic fallback.
        role: "level",
        group: "slow",
        write: true,
        min: -200,
        max: 200,
    },
    {
        id: "ems.battCtrlPowerTarget",
        name: "EMS BattCtrl charge/discharge power target (+charge/-discharge)",
        address: 50207,
        type: "s16",
        scale: 0.01,
        unit: "kW",
        role: "level",
        group: "slow",
        write: true,
        min: -200,
        max: 200,
    },
    {
        id: "ems.battCtrlMaxGridExport",
        name: "EMS BattCtrl max grid export power",
        address: 50208,
        type: "s16",
        scale: 0.01,
        unit: "kW",
        role: "level",
        group: "slow",
        write: true,
        min: 0,
        max: 200,
    },
    {
        id: "ems.battCtrlMaxGridImport",
        name: "EMS BattCtrl max grid import power",
        address: 50209,
        type: "s16",
        scale: 0.01,
        unit: "kW",
        role: "level",
        group: "slow",
        write: true,
        min: -200,
        max: 0,
    },
    {
        id: "ems.battCtrlPriorityOutput",
        name: "EMS BattCtrl priority of power output",
        address: 50210,
        type: "map",
        role: "level",
        group: "slow",
        write: true,
        map: { 0: "PV", 1: "Battery" },
    },
    {
        id: "ems.batterySocMinOnGrid",
        name: "Battery SOC min (on-grid)",
        address: 52503,
        type: "u16",
        scale: 0.1,
        unit: "%",
        role: "level.battery",
        group: "slow",
        write: true,
        min: 5,
        max: 100,
    },
    {
        id: "ems.batterySocMinOffGrid",
        name: "Battery SOC min (off-grid)",
        address: 52505,
        type: "u16",
        scale: 0.1,
        unit: "%",
        role: "level.battery",
        group: "slow",
        write: true,
        min: 5,
        max: 100,
    },
    {
        id: "ems.batteryChargeCurrentLimit",
        name: "Battery charge current limit (setpoint)",
        address: 52601,
        type: "u16",
        scale: 0.1,
        unit: "A",
        role: "level.current",
        group: "slow",
        write: true,
        min: 0,
        max: 200,
    },
    {
        id: "ems.batteryDischargeCurrentLimit",
        name: "Battery discharge current limit (setpoint)",
        address: 52603,
        type: "u16",
        scale: 0.1,
        unit: "A",
        role: "level.current",
        group: "slow",
        write: true,
        min: 0,
        max: 200,
    },
    {
        id: "ems.chargeCutoffSoc",
        name: "Charge cutoff SOC",
        address: 52506,
        type: "u16",
        scale: 0.1, // the register is READ in 0.1 % (raw 1000 = 100.0 %) ...
        writeScale: 1, // ... but WRITTEN in whole percent (reference implementation: read_scale 0.1, scale 1)
        unit: "%",
        role: "level.battery",
        group: "slow",
        write: true,
        min: 10,
        max: 98,
    },
    {
        id: "ems.exportLimitSwitch",
        name: "Export limit switch",
        address: 25100,
        // role "switch" requires common.type=boolean per the ioBroker state-roles spec.
        type: "bool",
        role: "switch",
        group: "slow",
        write: true,
    },
    {
        id: "ems.exportLimitValue",
        name: "Export limit value",
        address: 25103,
        type: "s16",
        scale: 0.1,
        unit: "%",
        role: "level",
        group: "slow",
        write: true,
        min: -100,
        max: 500,
    },
    {
        id: "ems.importLimitSwitch",
        name: "Import limit switch",
        address: 50007,
        type: "bool",
        role: "switch",
        group: "slow",
        write: true,
    },
    {
        id: "ems.importLimitValue",
        name: "Import limit value",
        address: 50009,
        type: "u16",
        scale: 0.1,
        unit: "kW",
        role: "level",
        group: "slow",
        write: true,
        min: 0,
        max: 100,
    },
    {
        id: "ems.offGridSwitch",
        name: "Off-grid command (write true = force off-grid, false = on-grid; the register reads 0xFFFF when no command is pending, which is not published)",
        address: 50200,
        type: "bool",
        role: "switch",
        group: "slow",
        write: true,
        ignoreRaw: [0xffff],
    },

    // ---- Additional registers found by reading the inverter (2026-10-05) ----
    // All of them answered on a real MHT-25~50K-100; addresses and scales from the reference
    // implementation (wills106/homeassistant-solax-modbus, plugin_solinteg.py).
    {
        id: "energy.acGenerationToday",
        name: "AC energy generated today (inverter output incl. battery discharge)",
        address: 11018,
        type: "u32",
        scale: 0.1,
        unit: "kWh",
        role: "value.energy",
        group: "slow",
    },
    {
        id: "energy.acGenerationTotal",
        name: "AC energy generated total",
        address: 11020,
        type: "u32",
        scale: 0.1,
        unit: "kWh",
        role: "value.energy",
        group: "slow",
    },
    {
        id: "diag.temperatureR",
        name: "Inverter temperature phase R",
        address: 11032,
        type: "s16",
        scale: 0.1,
        unit: "°C",
        role: "value.temperature",
        group: "slow",
    },
    {
        id: "diag.temperatureS",
        name: "Inverter temperature phase S",
        address: 11033,
        type: "s16",
        scale: 0.1,
        unit: "°C",
        role: "value.temperature",
        group: "slow",
    },
    {
        id: "diag.temperatureT",
        name: "Inverter temperature phase T",
        address: 11034,
        type: "s16",
        scale: 0.1,
        unit: "°C",
        role: "value.temperature",
        group: "slow",
    },
    {
        id: "diag.operationFlags",
        name: "Operation flags (bitmask: bit 14 off-grid, bit 5 battery abnormal, bit 3 mains abnormal, ...)",
        address: 10110,
        type: "u32",
        role: "value",
        group: "slow",
    },
    {
        id: "diag.armFaultFlags1",
        name: "ARM fault flags 1 (bitmask)",
        address: 18000,
        type: "u32",
        role: "value",
        group: "slow",
    },
    {
        id: "diag.armFaultFlags2",
        name: "ARM fault flags 2 (bitmask)",
        address: 18004,
        type: "u32",
        role: "value",
        group: "slow",
    },
    {
        id: "grid.backupPower",
        name: "Backup port power",
        address: 30230,
        type: "s32",
        unit: "W",
        role: "value.power",
        group: "fast",
    },
    {
        id: "meter.gridExportToday",
        name: "Grid export today",
        address: 31000,
        type: "u16",
        scale: 0.1,
        unit: "kWh",
        role: "value.energy",
        group: "slow",
    },
    {
        id: "meter.gridImportToday",
        name: "Grid import today",
        address: 31001,
        type: "u16",
        scale: 0.1,
        unit: "kWh",
        role: "value.energy",
        group: "slow",
    },
    // ---- EMS settings that read back correctly on this firmware (write needs EMS write access) ----
    {
        id: "ems.upsFunction",
        name: "UPS function enabled",
        address: 50001,
        type: "bool",
        role: "switch",
        group: "slow",
        write: true,
    },
    {
        id: "ems.gridUnbalancedOutput",
        name: "Grid unbalanced output enabled",
        address: 50006,
        type: "bool",
        role: "switch",
        group: "slow",
        write: true,
    },
    {
        id: "ems.batteryProtectionRelax",
        name: "Battery protection relax enabled",
        address: 50012,
        type: "bool",
        role: "switch",
        group: "slow",
        write: true,
    },
    {
        id: "ems.batterySocProtectionOnGrid",
        name: "Battery SOC protection on grid enabled",
        address: 52502,
        type: "bool",
        role: "switch",
        group: "slow",
        write: true,
    },
    {
        id: "ems.batterySocProtectionOffGrid",
        name: "Battery SOC protection off grid enabled",
        address: 52504,
        type: "bool",
        role: "switch",
        group: "slow",
        write: true,
    },
    {
        id: "ems.acCtrlPhaseAPower",
        name: "EMS AC control phase A power scheduling",
        address: 50204,
        type: "s16",
        scale: 0.01,
        unit: "kW",
        role: "level",
        group: "slow",
        write: true,
        min: -200,
        max: 200,
    },
    {
        id: "ems.acCtrlPhaseBPower",
        name: "EMS AC control phase B power scheduling",
        address: 50205,
        type: "s16",
        scale: 0.01,
        unit: "kW",
        role: "level",
        group: "slow",
        write: true,
        min: -200,
        max: 200,
    },
    {
        id: "ems.acCtrlPhaseCPower",
        name: "EMS AC control phase C power scheduling",
        address: 50206,
        type: "s16",
        scale: 0.01,
        unit: "kW",
        role: "level",
        group: "slow",
        write: true,
        min: -200,
        max: 200,
    },
];

const registersById = new Map(registers.map((def) => [def.id, def]));

module.exports = { registers, registersById, PV_STRINGS };
